# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1492650832);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1492650952);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1492654072);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1492650712);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1492650592);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1492651072);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 225280);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1494708689150");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1494710501150");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1494708689691");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1494712289691");
user_pref("browser.search.countryCode", "SV");
user_pref("browser.search.region", "SV");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20170126195238");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20170126195238");
user_pref("browser.startup.homepage_override.mstone", "45.7.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1487123637228");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1487037298861");
user_pref("datareporting.policy.firstRunTime", "1487037237227");
user_pref("datareporting.sessions.current.activeTicks", 13);
user_pref("datareporting.sessions.current.firstPaint", 4467);
user_pref("datareporting.sessions.current.main", 1630);
user_pref("datareporting.sessions.current.sessionRestored", 5863);
user_pref("datareporting.sessions.current.startTime", "1494708677371");
user_pref("datareporting.sessions.current.totalTime", 70);
user_pref("datareporting.sessions.currentIndex", 14);
user_pref("datareporting.sessions.prunedIndex", 13);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 8);
user_pref("extensions.blocklist.pingCountVersion", 8);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"langpack-es-AR@firefox.mozilla.org\":{\"version\":\"45.7.0\",\"type\":\"locale\",\"descriptor\":\"/home/wmolina/.mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/langpack-es-AR@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.7.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1492650833);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.7.0");
user_pref("extensions.lastPlatformVersion", "45.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib64/firefox/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1485461158000}},\"app-system-user\":{\"langpack-es-AR@firefox.mozilla.org\":{\"d\":\"/home/wmolina/.mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/langpack-es-AR@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"45.7.0\",\"st\":1485461210000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.7.0\",\"st\":1485461157000}}}");
user_pref("gecko.buildID", "20170126195238");
user_pref("gecko.mstone", "45.7.0");
user_pref("idle.lastDailyNotification", 1494708799);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1487037300);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20170126195238");
user_pref("media.gmp-manager.lastCheck", 1494708742);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1492650636);
user_pref("places.history.expiration.transient_current_max_pages", 12578);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1490058962);
user_pref("toolkit.startup.last_success", 1494708679);
user_pref("toolkit.telemetry.cachedClientID", "ced65590-4b39-46b9-9bc7-e3a079bfed21");
user_pref("toolkit.telemetry.previousBuildID", "20170126195238");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
